#!/bin/bash

if (( $# == 2 ));
then
    pkdeltak=$(skcompute $2 | tail -1)
    echo $1 $pkdeltak | xargs src/Gcompute
else
    pkdeltak=$(skcompute $1 | tail -1)
    echo "-v" $pkdeltak | xargs src/Gcompute
fi	



