#!/bin/bash

while getopts v flag; do
    VERBOSE=1
done

shift $(( OPTIND - 1 ));

if (( $1 > 10 )); then
   if [ $VERBOSE ]; then
       src/sjcompute -v $1 | tail -1 | xargs src/adjust_sx_delta 
   else
       src/sjcompute $1 | xargs src/adjust_sx_delta 
   fi
fi

#echo $1 "less than 11"

if (( $1 == 2 )); then
    echo 2 0
    exit 0
fi

if (( $1 == 3 )); then
    echo 2 1
    exit 0
fi


if (( $1 == 4 )); then
    echo 2 2
    exit 0
fi

if (( $1 == 5 )); then
    echo 3 0
    exit 0
fi

if (( $1 == 6 )); then
    echo 3 1
    exit 0
fi

if (( $1 == 7 )); then
    echo 3 2
    exit 0
fi

if (( $1 == 8 )); then
    echo 3 3
    exit 0
fi

if (( $1 == 9 )); then
    echo 3 4
    exit 0
fi

if (( $1 == 10 )); then
    echo 5 0
    exit 0
fi
